### ISSUE TITLE
Issues with recipe item non-integer counts

### ISSUE THREAD

**Issue by FlareLine** [NotEnoughUpdates/NotEnoughUpdates-REPO#1286]
Hi there!

NEU looks to this repository to load various items and recipes. When launching the mod, it looks like some items contain non-integer counts for items within recipes. This causes `NumberFormatExceptions` (which are ultimately swallowed to prevent crashing). See below for an example:

```
[io.github.moulberry.notenoughupdates.NEUManager:loadItem:361]: internalName is : UMBER_PLATE
java.lang.NumberFormatException: For input string: "4.0"
  at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
  at java.lang.Integer.parseInt(Integer.java:580)
  at java.lang.Integer.parseInt(Integer.java:615)
  at io.github.moulberry.notenoughupdates.recipes.Ingredient.<init>(Ingredient.java:45)
  at io.github.moulberry.notenoughupdates.recipes.ForgeRecipe.parseForgeRecipe(ForgeRecipe.java:221)
  at io.github.moulberry.notenoughupdates.recipes.RecipeType.createRecipe(RecipeType.java:65)
  at io.github.moulberry.notenoughupdates.recipes.NeuRecipe.parseRecipe(NeuRecipe.java:79)
  at io.github.moulberry.notenoughupdates.NEUManager.loadItem(NEUManager.java:313)
...
```

The `Ingredient constructor fails to handle a count with a decimal part (even if this part is `.0`):

```
// Ingredient::init(NEUManager, String)
...
if (parts.length == 2) {
  count = Integer.parseInt(parts[1]); // This fails if the count is 'integer-like' but with decimal parts (eg. '4.0').
}
...
```

`UMBER_PLATE` looks to contain such values:
```
"inputs": [
  "REFINED_UMBER:4.0",
  "GLACITE_AMALGAMATION:1.0"
],
```

I would suggest that the fix for this bug would be to update the item recipes to remove the decimal part.

**Comment by NopoTheGamer** [comment]
Update the mod https://github.com/NotEnoughUpdates/NotEnoughUpdates/releases/tag/2.3.0
